random_seed = 42
experiment_config_path = "./experiment.toml"
model_save_dir = "./models"
eval_results_path = "./eval_results.json"

### DATASETS ###

[[datasets]]
name = "dataset_01"
data_dir = "./data/PetImages/"

    [[datasets.transforms]]
    name = "Resize"
    args = [[224, 224]]

    [[datasets.transforms]]
    name = "RandomHorizontalFlip"
    args = [0.5]

    [[datasets.transforms]]
    name = "ToTensor"


### MODELS ###

[[models]]
name = "model_01"
type = "BaselineModel"
[models.kwargs]
input_shape = 784
hidden_units = 10
output_shape = 10


[[models]]
name = "model_02"
type = "CNNModel"
[models.kwargs]
input_shape = 1
hidden_units = 10
output_shape = 10

### TRAINERS ###

[[trainers]]
name = "trainer_01"
epochs = 50
device = "cuda"
[trainers.loss_fn]
type = "CrossEntropyLoss"
kwargs = {}
[trainers.optimizer]
type = "Adam"
kwargs = {lr = 0.003}


[[trainers]]
name = "trainer_02"
epochs = 50
device = "cuda"
[trainers.loss_fn]
type = "CrossEntropyLoss"
kwargs = {}
[trainers.optimizer]
type = "SGD"
kwargs = {lr = 0.003}

### EVALUATORS ###

[[evaluators]]
name = "eval_01"
device = "cuda"
[evaluators.loss_fn]
type = "CrossEntropyLoss"
kwargs = {}
