random_seed = 42
pipeline_config_path = "./pipeline.toml"
model_save_dir = "./models"
eval_results_path = "./eval_results.json"

### MODELS ###

[[models]]
name = "model_01"
type = "BaselineModel"
[models.args]
input_shape = 784
hidden_units = 10
output_shape = 10


[[models]]
name = "model_02"
type = "CNNModel"
[models.args]
input_shape = 1
hidden_units = 10
output_shape = 10

### TRAINERS ###

[[trainers]]
name = "trainer_01"
epochs = 50
device = "cuda"
[trainers.loss_fn]
type = "CrossEntropyLoss"
args = {}
[trainers.optimizer]
type = "Adam"
args = {lr = 0.003}


[[trainers]]
name = "trainer_02"
epochs = 50
device = "cuda"
[trainers.loss_fn]
type = "CrossEntropyLoss"
args = {}
[trainers.optimizer]
type = "SGD"
args = {lr = 0.003}

### EVALUATORS ###

[[evaluators]]
name = "eval_01"
device = "cuda"
[evaluators.loss_fn]
type = "CrossEntropyLoss"
args = {}
